// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Wagmi from "wagmi";
import * as Router from "../Router.res.mjs";
import * as NameContext from "../NameContext.res.mjs";
import * as ProfileView from "./ProfileView.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

var UseAccount = {};

function Profile(props) {
  var profileName = props.profileName;
  var match = NameContext.use();
  var primaryName = match.primaryName;
  var account = Wagmi.useAccount();
  if (profileName !== undefined) {
    return React.createElement(ProfileView.make, {
                name: profileName
              });
  } else {
    React.useEffect((function () {
            if (!account.isConnected || Core__Option.isNone(primaryName)) {
              RescriptReactRouter.push(Router.toUrl("Home"));
            }
            
          }), [
          account.isConnected,
          primaryName
        ]);
    if (primaryName !== undefined) {
      return React.createElement(ProfileView.make, {
                  name: primaryName.name
                });
    } else {
      return null;
    }
  }
}

var make = Profile;

export {
  UseAccount ,
  make ,
}
/* react Not a pure module */
