// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Rainbowkit from "@rainbow-me/rainbowkit";

var Custom = {};

var ConnectButton = {
  Custom: Custom
};

function MyConnectButton(props) {
  return React.createElement(Rainbowkit.ConnectButton.Custom, {
              children: (function (props) {
                  var connected = props.mounted && Core__Option.isSome(props.account) && Core__Option.isSome(props.chain);
                  var ariaHidden = connected ? false : true;
                  var style = connected ? ({}) : ({
                        opacity: "0",
                        userSelect: "none",
                        pointerEvents: "none"
                      });
                  return React.createElement("div", {
                              "aria-hidden": ariaHidden,
                              style: style
                            });
                })
            });
}

var make = MyConnectButton;

export {
  ConnectButton ,
  make ,
}
/* react Not a pure module */
