// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icons from "./Icons.res.mjs";
import * as React from "react";
import * as Constants from "../Constants.res.mjs";
import ConfettiReact from "confetti-react";

function ResultPanel(props) {
  var onRegisterAnother = props.onRegisterAnother;
  return React.createElement("div", {
              className: "bg-white rounded-custom shadow-lg overflow-hidden"
            }, React.createElement("div", {
                  className: "p-6"
                }, React.createElement("div", {
                      className: "flex flex-col items-center text-center"
                    }, React.createElement("div", {
                          className: "mb-4"
                        }, React.createElement(Icons.Success.make, {
                              className: "w-16 h-16 text-green-500"
                            })), React.createElement("h2", {
                          className: "text-2xl font-bold mb-2"
                        }, "Registration Successful!"), React.createElement("p", {
                          className: "text-lg text-gray-700 mb-6"
                        }, React.createElement(ConfettiReact, {
                              recycle: false
                            }), props.registeredName + "." + Constants.sld), React.createElement("button", {
                          className: "py-3 px-6 bg-zinc-800 hover:bg-zinc-700 text-white rounded-2xl font-medium",
                          onClick: (function (param) {
                              onRegisterAnother();
                            })
                        }, "Register Another Name"))));
}

var make = ResultPanel;

export {
  make ,
}
/* Icons Not a pure module */
