// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ThemeContext from "../ThemeContext.res.mjs";

function ThemeToggle$SunIcon(props) {
  return React.createElement("svg", {
              height: "20",
              width: "20",
              fill: "none",
              stroke: "currentColor",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("circle", {
                  cx: "12",
                  cy: "12",
                  r: "5"
                }), React.createElement("line", {
                  x1: "12",
                  x2: "12",
                  y1: "1",
                  y2: "3"
                }), React.createElement("line", {
                  x1: "12",
                  x2: "12",
                  y1: "21",
                  y2: "23"
                }), React.createElement("line", {
                  x1: "4.22",
                  x2: "5.64",
                  y1: "4.22",
                  y2: "5.64"
                }), React.createElement("line", {
                  x1: "18.36",
                  x2: "19.78",
                  y1: "18.36",
                  y2: "19.78"
                }), React.createElement("line", {
                  x1: "1",
                  x2: "3",
                  y1: "12",
                  y2: "12"
                }), React.createElement("line", {
                  x1: "21",
                  x2: "23",
                  y1: "12",
                  y2: "12"
                }), React.createElement("line", {
                  x1: "4.22",
                  x2: "5.64",
                  y1: "19.78",
                  y2: "18.36"
                }), React.createElement("line", {
                  x1: "18.36",
                  x2: "19.78",
                  y1: "5.64",
                  y2: "4.22"
                }));
}

var SunIcon = {
  make: ThemeToggle$SunIcon
};

function ThemeToggle$MoonIcon(props) {
  return React.createElement("svg", {
              height: "20",
              width: "20",
              fill: "none",
              stroke: "currentColor",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("path", {
                  d: "M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"
                }));
}

var MoonIcon = {
  make: ThemeToggle$MoonIcon
};

function ThemeToggle(props) {
  var match = ThemeContext.useTheme();
  var setTheme = match.setTheme;
  var toggleTheme = function (param) {
    setTheme(function (currentTheme) {
          if (currentTheme === "Light") {
            return "Dark";
          } else {
            return "Light";
          }
        });
  };
  var tmp;
  tmp = match.theme === "Light" ? React.createElement(ThemeToggle$MoonIcon, {}) : React.createElement(ThemeToggle$SunIcon, {});
  return React.createElement("button", {
              "aria-label": "Toggle theme",
              className: "p-2 rounded-full bg-gray-200 dark:bg-dark-accent text-gray-800 dark:text-dark-text hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors",
              onClick: toggleTheme
            }, tmp);
}

var make = ThemeToggle;

export {
  SunIcon ,
  MoonIcon ,
  make ,
}
/* react Not a pure module */
