// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Wagmi from "wagmi";
import * as Chains from "wagmi/chains";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactQuery from "@tanstack/react-query";
import * as Rainbowkit from "@rainbow-me/rainbowkit";

var queryClient = new ReactQuery.QueryClient();

var transports = new Map();

transports.set(Chains.koi.id, Wagmi.http());

var config = Rainbowkit.getDefaultConfig({
      appName: "Subnames App",
      projectId: "873f70fa626990b1ee3c14d55130a573",
      chains: [Chains.koi],
      transports: transports,
      ssr: false
    });

function App(props) {
  return JsxRuntime.jsx(Wagmi.WagmiProvider, {
              config: config,
              children: JsxRuntime.jsx(ReactQuery.QueryClientProvider, {
                    client: queryClient,
                    children: JsxRuntime.jsx(Rainbowkit.RainbowKitProvider, {
                          children: JsxRuntime.jsx(Rainbowkit.ConnectButton, {})
                        })
                  })
            });
}

var make = App;

export {
  make ,
}
/* queryClient Not a pure module */
