// Generated by ReScript, PLEASE EDIT WITH CARE


var sld = "darwinia.eth";

var registryContractAddress = "0x807a3e011DF1785c538Ac6F65252bf740678Ff99";

var baseRegistrarContractAddress = "0x74b673e8cb4894D926d5c7bD35B472f88E998468";

var reverseRegistrarContractAddress = "0x0222fC117531519Ff9F4941F1299b1e222645166";

var controllerContractAddress = "0xa9EA0B4Fc053c68977F535Ea67e3f0062B363443";

var resolverContractAddress = "0xf761709777A4aa1b71570524869B1876fEafCB2e";

var parentNode = "0xa00b30653aa21de4caea57dc656dcab595a7f3a936e0564ffc5dd8448b945581";

var rpcUrl = "https://crab-rpc.darwinia.network";

var indexerUrl = "https://g2d.site/graphql";

var metricsUrl = "https://g2d.site/metrics";

export {
  sld ,
  registryContractAddress ,
  baseRegistrarContractAddress ,
  reverseRegistrarContractAddress ,
  controllerContractAddress ,
  resolverContractAddress ,
  parentNode ,
  rpcUrl ,
  indexerUrl ,
  metricsUrl ,
}
/* No side effect */
