// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./Constants.res.mjs";
import * as OnChainOperations from "./OnChainOperations.res.mjs";

async function calculate(name, years) {
  var duration = Math.imul(years, Constants.secondsPerYear);
  var priceInWei = await OnChainOperations.registerPrice(name, duration);
  console.log("name: \"" + name + "\", duration: " + duration.toString() + ", price: " + priceInWei.toString());
  return (Number(priceInWei) / 10e18).toFixed(8);
}

export {
  calculate ,
}
/* OnChainOperations Not a pure module */
