// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as React from "react";
import * as Client from "react-dom/client";

import './index.css'
;

import '@rainbow-me/rainbowkit/styles.css'
;

var domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }));
}

export {
  
}
/*  Not a pure module */
