// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var context = React.createContext({
      forceRefresh: false,
      setForceRefresh: (function (param) {
          
        }),
      primaryName: undefined,
      setPrimaryName: (function (param) {
          
        })
    });

var make = context.Provider;

var Provider = {
  make: make
};

function use() {
  return React.useContext(context);
}

export {
  context ,
  Provider ,
  use ,
}
/* context Not a pure module */
