// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./Constants.res.mjs";
import * as OnChainOperationsCommon from "./OnChainOperationsCommon.res.mjs";

var reverseRegistrarContract = {
  address: Constants.reverseRegistrarContractAddress,
  abi: [{
      type: "function",
      name: "setName",
      inputs: [{
          name: "name",
          type: "string"
        }],
      outputs: [{
          name: "",
          type: "bytes32"
        }],
      stateMutability: "nonpayable"
    }]
};

async function setName(walletClient, name) {
  var currentAddress = await OnChainOperationsCommon.currentAddress(walletClient);
  var match = await OnChainOperationsCommon.publicClient.simulateContract({
        account: currentAddress,
        address: reverseRegistrarContract.address,
        abi: reverseRegistrarContract.abi,
        functionName: "setName",
        args: [name]
      });
  var hash = await walletClient.writeContract(match.request);
  var match$1 = await OnChainOperationsCommon.publicClient.waitForTransactionReceipt({
        hash: hash
      });
  console.log(hash + " confirmed in block " + match$1.blockNumber.toString() + ", status: " + match$1.status);
}

export {
  reverseRegistrarContract ,
  setName ,
}
/* OnChainOperationsCommon Not a pure module */
