// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./Constants.res.mjs";

function fromUrl(url) {
  var match = url.path;
  if (!match) {
    return "Home";
  }
  var name = match.hd;
  switch (name) {
    case "names" :
        if (match.tl) {
          return "NotFound";
        } else {
          return "Names";
        }
    case "profile" :
        if (match.tl) {
          return "NotFound";
        } else {
          return "Profile";
        }
    default:
      if (match.tl) {
        return "NotFound";
      }
      if (!new RegExp("^@.+" + Constants.sld + "$").test(name)) {
        return "NotFound";
      }
      var name$1 = name.substring(1).split(".")[0];
      return {
              TAG: "ProfileView",
              _0: name$1
            };
  }
}

function toUrl(route) {
  if (typeof route === "object") {
    return "/@" + route._0;
  }
  switch (route) {
    case "Home" :
        return "/";
    case "Names" :
        return "/names";
    case "Profile" :
        return "/profile";
    case "NotFound" :
        return "/404";
    
  }
}

export {
  fromUrl ,
  toUrl ,
}
/* No side effect */
