// Generated by ReScript, PLEASE EDIT WITH CARE


function fromUrl(url) {
  var match = url.path;
  if (!match) {
    return "Home";
  }
  switch (match.hd) {
    case "names" :
        if (match.tl) {
          return "NotFound";
        } else {
          return "Names";
        }
    case "profile" :
        if (match.tl) {
          return "NotFound";
        } else {
          return "Profile";
        }
    default:
      return "NotFound";
  }
}

function toUrl(route) {
  switch (route) {
    case "Home" :
        return "/";
    case "Names" :
        return "/names";
    case "Profile" :
        return "/profile";
    case "NotFound" :
        return "/404";
    
  }
}

export {
  fromUrl ,
  toUrl ,
}
/* No side effect */
