// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as InputPanel from "./components/InputPanel.res.mjs";
import * as NameContext from "./NameContext.res.mjs";
import * as ResultPanel from "./components/ResultPanel.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as RegisterPanel from "./components/RegisterPanel.res.mjs";

var initialState = {
  name: "",
  panel: "input",
  registeredName: undefined
};

function SubnameInput(props) {
  var match = NameContext.use();
  var setUpdateName = match.setUpdateName;
  var match$1 = React.useState(function () {
        return initialState;
      });
  var setState = match$1[1];
  var state = match$1[0];
  var onRegisterSuccess = function (name) {
    setState(function (prev) {
          return {
                  name: prev.name,
                  panel: "result",
                  registeredName: name
                };
        });
    setUpdateName(function (param) {
          return true;
        });
  };
  var match$2 = state.panel;
  var tmp;
  switch (match$2) {
    case "input" :
        tmp = React.createElement(InputPanel.make, {
              onNext: (function (name) {
                  setState(function (prev) {
                        return {
                                name: name,
                                panel: "register",
                                registeredName: prev.registeredName
                              };
                      });
                })
            });
        break;
    case "register" :
        tmp = React.createElement(RegisterPanel.make, {
              name: state.name,
              isWalletConnected: props.isWalletConnected,
              onBack: (function () {
                  setState(function (prev) {
                        return {
                                name: prev.name,
                                panel: "input",
                                registeredName: prev.registeredName
                              };
                      });
                }),
              onRegisterSuccess: onRegisterSuccess
            });
        break;
    case "result" :
        tmp = React.createElement(ResultPanel.make, {
              registeredName: Core__Option.getOr(state.registeredName, ""),
              onRegisterAnother: (function () {
                  setState(function (param) {
                        return initialState;
                      });
                })
            });
        break;
    default:
      tmp = React.createElement("div", undefined);
  }
  return React.createElement("div", {
              className: "w-full max-w-xl mx-auto"
            }, tmp);
}

var make = SubnameInput;

export {
  make ,
}
/* react Not a pure module */
