// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var context = React.createContext({
      theme: "Light",
      setTheme: (function (param) {
          
        })
    });

var make = context.Provider;

var Provider = {
  make: make
};

function useTheme() {
  return React.useContext(context);
}

function applyTheme(theme) {
  if (theme === "Light") {
    document.documentElement.className = "light";
    return ;
  }
  document.documentElement.className = "dark";
}

function getInitialTheme() {
  return "Dark";
}

export {
  context ,
  Provider ,
  useTheme ,
  applyTheme ,
  getInitialTheme ,
}
/* context Not a pure module */
