// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function useDebounce(callback, delay) {
  var timeoutRef = React.useRef(undefined);
  return function (value) {
    var timeout = timeoutRef.current;
    if (timeout !== undefined) {
      clearTimeout(Caml_option.valFromOption(timeout));
    }
    var timeout$1 = setTimeout((function () {
            callback(value);
          }), delay);
    timeoutRef.current = Caml_option.some(timeout$1);
  };
}

export {
  useDebounce ,
}
/* react Not a pure module */
